# This file is used to configure the Render service for the Aftab Portfolio project.
# It specifies the services, environment variables, and build commands needed to run the application.
services:
  - type: web
    name: aftab-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
